# Generated by Django 3.0.9 on 2023-04-07 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='tile',
            options={'ordering': ['-launch_date']},
        ),
        migrations.AlterField(
            model_name='tile',
            name='launch_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 15, 54, 5, 598891, tzinfo=utc)),
        ),
    ]
